In [1]:
#1. Create a 3×3 NumPy array of all True.

import numpy as np
Array = np.ones((3, 3), dtype=bool)
print(Array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [2]:
#2. Create a 1D array of 10 evenly spaced values between 5 and 50.

import numpy as np
Array = np.linspace(5, 50, 10)
print(Array)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [3]:
#3. Convert a Python list into a NumPy array.

import numpy as np
List = [10, 20, 30, 40, 50]
Array = np.array(List)
print(Array)

[10 20 30 40 50]


In [4]:
#4. Reverse a 1D NumPy array.

import numpy as np
Array = np.array([10, 20, 30, 40, 50])
Reverse = Array[::-1]
print(Reverse)

[50 40 30 20 10]


In [5]:
#5. Create a 3×3 identity matrix.

import numpy as np
Array = np.eye(3)
print(Array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#6. Create a 4×4 array and extract its first row and last column.

import numpy as np
Array = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
First_Row = Array[0, :]
Last_Column = Array[:, -1]
print("First Row:", First_Row)
print("Last Column:", Last_Column)

First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]


In [8]:
#7. Write a code to Create a 4×4 NumPy array and extract the first two rows and first two columns.

import numpy as np
Array = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
Result = Array[0:2, 0:2]
print(Result)

[[1 2]
 [5 6]]


In [10]:
#8. Perform arithmetic operations on two NumPy arrays element-wise.

import numpy as np
A = np.array([10, 20, 30])
B = np.array([5, 10, 15])
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)

Addition: [15 30 45]
Subtraction: [ 5 10 15]
Multiplication: [ 50 200 450]
Division: [2. 2. 2.]


In [11]:
#9. Write a code to compute the dot product of two NumPy arrays.

import numpy as np
A = np.array([10, 20, 30])
B = np.array([40, 50, 60])
Dot_Product = np.dot(A, B)
print("Dot Product:", Dot_Product)

Dot Product: 3200


In [13]:
#10. Compute the mean, median, and standard deviation of a NumPy array.

import numpy as np
Array = np.array([1, 2, 3, 4, 5])
Mean = np.mean(Array)
Median = np.median(Array)
Standard_Deviation = np.std(Array)
print("Mean:", Mean)
print("Median:", Median)
print("Standard Deviation:", Standard_Deviation)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
